### ISSUE TITLE
Version 1.7.7 not comaptible

### ISSUE THREAD

**Issue by markoopapa** [mobilpay/prestashop#3]
Is not compatible with version 1.7.7. More bugs. need to be solved fast.

**Comment by theeldermaster** [comment]
I confirm also that is a big problem with the compatibility of Prestashop 1.7.7.1 with the MobilPay module.
After the payment is processed no invoice is generated and the status in not available in front office on order history or in backoffice - Orders List. 
Unfortunately this is a BIG drawback and we were close to sign the contract with Netopia.
If they don't solve fast we switch to another company. I happy that we are in 2021 and we can choose now more fast.
Time 2 Market is very important.
We like Mobilpay but with this bug is impossible to go further.

**Comment by navid59** [comment]
Thank you so much for letting us know about this.
A new plugin will coming soon for Prestashop version 1.7.7.1 witch will cover the problems on 1.7.7 as well.

**Comment by navid59** [comment]
There is a new Prestashop module, on the NETOPIA Payments platform.
Please login to your account , and download the  Module

**Comment by storygram** [comment]
I am trying to install this module on Prestashop version 1.7.7.4 and it does not work, please help me

**Comment by navid59** [comment]
Thank you for letting us know about it
Please , share if you have any special error / notification.

**Comment by storygram** [comment]
That's all it gives me:

error
Oops ... Upload failed.

What happened?

**Comment by navid59** [comment]
You have no permission to upload the file
Check the permission of the directory.

Please, follow the steps in document 
https://github.com/mobilpay/prestashop/blob/master/Docs/manual_install_EN%20v.1.7.pdf
